######################################################
# Changing raster resolution and produce binary maps #
######################################################

# 26/07/2016 : Roxanne Leberger

# using gosling (server)

cd ../..

cd net/netmonde1/vol/vol17/leberro-processing/esh_Graeme/

# mv  *_12.tif ../moll_1_2_12/ 


# build list to work on in grass
cd moll_1_2_12/
ls *_1.tif > birds_1_list.txt # replace _out by nothing to not do same computation twice

cd moll_1_2_12/
ls *_2.tif > birds_2_list.txt

cd moll_1_2_12/
ls *_12.tif > birds_12_list.txt 

# import list changing resolution

grass70

birds=$(cat "birds_1_list.txt")        #the output of 'cat $file' is assigned to the $name variable
echo $birds  

birds=$(cat "birds_2_list.txt")        #the output of 'cat $file' is assigned to the $name variable
echo $birds  

birds=$(cat "birds_12_list.txt")        #the output of 'cat $file' is assigned to the $name variable
echo $birds  


# loop: resolution
g.region res=100000

for file in  $birds; do 
	r.in.gdal in=$file'.tif' out=$file --o
	r.resamp.stats input=$file  output=$file'_100km'  method=average --o
	r.null map=$file'_100km' null=0 --o
done;

d.mon wx0
d.rast mol_esh_22678135_1_100km # ok
d.rast mol_esh_22678135_1 # ok 


# generate binary rasters (1/0 => presence/abs)
##

# r.mapcalc and r.reclass used by sh namefile.txt

cp birds_1_list.txt birds_1_list2.txt
paste birds_1_list.txt birds_1_list2.txt > rmapcalc_birds_1_list.txt
head rmapcalc_birds_1_list.txt
gedit rmapcalc_birds_1_list.txt # transform the names to have the command lines

cp birds_2_list.txt birds_2_list2.txt
paste birds_2_list.txt birds_2_list2.txt > rmapcalc_birds_2_list.txt

gedit rmapcalc_birds_2_list.txt

cp birds_12_list.txt birds_12_list2.txt
paste birds_12_list.txt birds_12_list2.txt > rmapcalc_birds_12_list.txt

gedit rmapcalc_birds_12_list.txt

# sh rmapcalc_birds_1_list.txt # execute the file
# sh rmapcalc_birds_2_list.txt # execute the file
# sh rmapcalc_birds_12_list.txt # execute the file

r.info mol_esh_22718333_1_100km2

# r.reclass
paste birds_1_list.txt birds_1_list2.txt > reclass_birds_1_list.txt
paste birds_2_list.txt birds_2_list2.txt > reclass_birds_2_list.txt
paste birds_12_list.txt birds_12_list2.txt > reclass_birds_12_list.txt

# sh reclass_birds_1_list.txt  # execute the file
# sh reclass_birds_2_list.txt 
# sh reclass_birds_12_list.txt 

r.info mol_esh_22718333_1_100km_bin

d.mon wx0 
d.rast mol_esh_22678135_1_100km_bin

# see % covered by forest script: birds_breeding_range
cp birds_list.txt birds_list2.txt
paste birds_list.txt birds_list2.txt > routgdal_birds_bin.txt
# sh routgdal_birds_bin.txt

g.list type=raster pattern=_bin
# sh g_remove_1.txt # to remove rasters generated by mistake...

# sum rasters
ls *.tif > birds_list.txt 

cp birds_list.txt rmapcalc_sum_birds_list.txt

# export rasters

